version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: contatouniville
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: dockerdemo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost/contatouniville?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo&useSSl=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
volumes:
  db_data: {}